# Имя нашего рабочего процесса, отображается в GitHub
name: Daily News Bot

# Условия запуска
on:
  # Запуск по расписанию: '0 7 * * *' означает "в 7:00 по UTC каждый день"
  # Вы можете поменять время. 7:00 UTC = 10:00 по Москве.
  schedule:
    - cron: '0 1 * * *'
  
  # Эта строчка позволяет запускать бота вручную с сайта GitHub для теста
  workflow_dispatch:

# Задачи, которые нужно выполнить
jobs:
  build-and-run:
    # Запускать на последней версии Ubuntu
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Скачиваем код из нашего репозитория
      - name: Checkout repository
        uses: actions/checkout@v4

      # Шаг 2: Устанавливаем Python нужной версии
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # Шаг 3: Устанавливаем библиотеки из файла requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Шаг 4: Запускаем наш основной скрипт
      - name: Run the bot script
        env:
          # Здесь мы безопасно передаем наши секреты в скрипт
          MEDIASTACK_API_KEY: ${{ secrets.MEDIASTACK_API_KEY }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHANNEL_ID: ${{ secrets.TELEGRAM_CHANNEL_ID }}
        run: python news_bot.py
